$lock_cmd = hyprctl dispatch 'hl.dsp.global("quickshell:lock")' & pidof qs quickshell hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    inhibit_sleep = 3
}

listener {
    timeout = 1800 # 60mins
    on-timeout = 1800loginctl lock-session
}

listener {
    timeout = 1800 # 2 hours
    on-timeout = 1800hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 1800 # 4 hours
    on-timeout = 1800$suspend_cmd
}
