exec-once = gsettings set org.gnome.desktop.interface icon-theme "breeze"
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
env = XCURSOR_THEME,Material-Cursor
windowrule = fullscreen, class:^(code)$

input {
    # Adjust this value from -1.0 to 1.0 (0 is default) to change pointer/touchpad speed
    sensitivity = 1.0
}
