hl.config({ general = { gaps_in = 2, gaps_out = 4, border_size = 1, allow_tearing = true, 
            resize_on_border = false, col = {
                active_border = "rgba(241f31ff)",
                inactive_border = "rgba(000000ff)",
            },
            layout = "dwindle",
        },
    decoration = {
            rounding = 8,
            blur = {
                enabled = false,
                size = 8,
                passes = 1,
                noise = 0.0117,
                contrast = 0.8916,
                brightness = 1.0,
            },
            shadow = {
                enabled = false,
                range = 20,
                render_power = 3,
            },
            dim_inactive = false,
            rounding_power = 2.0,
            active_opacity = 1.0,
            inactive_opacity = 1.0,
            dim_strength = 0.5,
        },
    input = {
            sensitivity = 1.0,
            accel_profile = "flat",
            kb_layout = "fr",
            kb_options = "",
            repeat_delay = 200,
            repeat_rate = 30,
            numlock_by_default = false,
            natural_scroll = false,
            left_handed = false,
            scroll_factor = 2.1,
            follow_mouse = 1,
            focus_on_close = 0,
            touchpad = {
                natural_scroll = true,
                disable_while_typing = true,
                tap_to_click = true,
                clickfinger_behavior = false,
                scroll_factor = 1.0,
                middle_button_emulation = false,
                tap_and_drag = true,
            },
        },
    cursor = {
            inactive_timeout = 0.0,
            no_hardware_cursors = false,
            hotspot_padding = 0,
            no_warps = false,
            persistent_warps = false,
            hide_on_key_press = false,
            hide_on_touch = false,
            zoom_factor = 1.0,
            zoom_rigid = false,
        },
    misc = {
            vrr = 2,
        },
    dwindle = {
            preserve_split = false,
            smart_split = false,
            smart_resizing = true,
            special_scale_factor = 1.0,
            default_split_ratio = 1.0,
        },
    master = {
            mfact = 0.55,
            new_status = "slave",
            orientation = "left",
            new_on_top = false,
            smart_resizing = true,
            allow_small_split = false,
        },
})
